name: Bug Report
description: Something isn't working as expected
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this! The more details you provide, the faster we can help.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear description of the bug
      placeholder: When I call session.initialize(), it hangs indefinitely...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
      description: What should have happened instead?
      placeholder: The session should initialize successfully and return an InitializeResult
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: How to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Create a client session with...
        2. Call session.initialize()
        3. Wait for response...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your setup details
      placeholder: |
        - conduit-mcp version: 0.1.0
        - Python version: 3.12.1
        - OS: macOS 14.0
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Anything else that might help us understand the issue
