name: Feature Request
description: Suggest an idea or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        We love hearing ideas for making conduit-mcp better! Help us understand what you're looking for.

  - type: textarea
    id: problem
    attributes:
      label: What problem are you trying to solve?
      description: Describe the use case or pain point
      placeholder: When building MCP servers, I often need to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: What would you like to see?
      description: Your ideal solution or API
      placeholder: |
        I'd love to see something like:
        ```python
        server.tools.register_batch([tool1, tool2, tool3])
        ```
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other approaches you've thought about
      placeholder: I could work around this by... but it would be much cleaner if...

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Anything else that would help us understand the request
